### ISSUE TITLE
conflicting versions of libssl/libssl-dev

### ISSUE THREAD

**Issue by cericoda** [UnsignedLong/ansible-nginx-letsencrypt#1]
Hi,

I ran this today with jessie 8.7, and it's now working perfectly, however I just thought I'd report that I had  the following issue:

libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u6) but 1.0.2k-1~bpo8+1 is to be installed

Which I had to resolve manually.

Many thanks for the playbook.

**Comment by UnsignedLong** [comment]
Reproducible - going to fix this. Thanks for reporting this issue.

**Comment by UnsignedLong** [comment]
Bug fixed. Confirmed working on naked debian jessie docker container.
