### ISSUE TITLE
increase expiry time?

### ISSUE THREAD

**Issue by cericoda** [UnsignedLong/ansible-nginx-letsencrypt#2]
Hi just a suggestion, the letsencrypt bot notifies expiry of certificates 19 days in advance.

Is it worth adjusting ssl_expiry_threshold default to 20 days so that upon receipt of this first email, the task can be run again and it will renew the cert?

**Comment by UnsignedLong** [comment]
Completely valid point!

**Comment by UnsignedLong** [comment]
Implemented.
