### ISSUE TITLE
failure on task setup letsencrypt dependencies

### ISSUE THREAD

**Issue by cericoda** [UnsignedLong/ansible-nginx-letsencrypt#3]
I am getting the following ignored error when trying to run the playbook :

TASK [nginx-letsencrypt-reverseproxy : setup letsencrypt dependencies] *********
fatal: [nginxproxy]: FAILED! => {"changed": true, "cmd": "/opt/letsencrypt/letsencrypt-auto", "delta": "0:00:02.114712", "end": "2017-06-10 13:59:06.016748", "failed": true, "rc": 1, "start": "2017-06-10 13:59:03.902036",
"stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nFailed to find executable apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\nCertbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run \"letsencrypt-auto certonly\" to do so. You'll need to manually configure your web server to use the resulting certificate.", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

Adding --os-packages-only to https://github.com/UnsignedLong/ansible-nginx-letsencrypt/blob/master/roles/nginx-letsencrypt-reverseproxy/tasks/main.yml#L37 seems to fix it, would you like me to add a pull request?

Thanks

**Comment by UnsignedLong** [comment]
Hi cericoda,

a PR would be great! Thanks in advance :)
